### ISSUE TITLE
No notifications

### ISSUE THREAD

**Issue by MissValeska** [naxuroqa/Venom#106]
I can't remember how many messages I've missed, How many conversations have abruptly ended, Because I was distracted, And had no way of knowing I got a message on venom, Unless I looked at the window directly.

Please please add some kind of notification feature, It doesn't have to be perfect right away, But just anything, Even if it is just a noise, That would be great! Though, If you can, A pop up in the corner with the beginning of the message, And the person who it came from would be great!

Thank you for reading :)

**Comment by naxuroqa** [comment]
Closing as outdated, there is now a basic notification feature using [GNotification](https://developer.gnome.org/gio/stable/GNotification.html)
