### ISSUE TITLE
Make it harder to close friend requests accidentally

### ISSUE THREAD

**Issue by Purrlite** [naxuroqa/Venom#124]
I got a friend request from TOX while I was tying something and the friend request got closed (assuming that I accidentally pressed cancel).

Could we make it harder to accidentally close the friend requests like this?

I would propose handling them sort of like Skype does by making the friend requests into new friend icons on the sidebar with a "?" icon (or some different one) instead of current status. Or maybe not making them grab focus (which should be easy, I think), so that whatever you are currently doing won't affect them.

**Comment by naxuroqa** [comment]
Closing as outdated, friend requests are being reworked
