### ISSUE TITLE
Friends and ID being reset after upgrading sometimes

### ISSUE THREAD

**Issue by Purrlite** [naxuroqa/Venom#128]
I'm not sure why, but when I or my friend upgrade Venom to latest build, sometimes our contacts (and usually ID too) gets reset and we have to add everyone again. It seems to still remember my nick after upgrading, but for some reason this doesn't apply to the ID.

Are we instealling it wrong or is this a bug?

**Comment by naxuroqa** [comment]
Closing as outdated
