### ISSUE TITLE
Lag in Ubuntu 13.10

### ISSUE THREAD

**Issue by MissValeska** [naxuroqa/Venom#134]
Venom lags when I go to another window, And then try to click on it again. Usually it will think it is still focused on, And then lose focus, And then get focus again. It takes quite a few seconds of clicking on what ever it is I want to actually click or select, Such as the chat box. It didn't always do this, And I'm sorry if this is vague, But, If you have any questions or tests for me to run, I will run them!

Thank you for reading!

**Comment by naxuroqa** [comment]
Closing as outdated
