### ISSUE TITLE
Dropdowns open offscreen on Windows when using a multi-monitor setup in which the primary display is not the leftmost display

### ISSUE THREAD

**Issue by c0z3n** [naxuroqa/Venom#14]
![broken setup](https://f.cloud.github.com/assets/1707218/1455959/789e3cf8-4322-11e3-8a7e-1bdeaf2c98a2.PNG)

![broken example](https://f.cloud.github.com/assets/1707218/1455955/66e35962-4322-11e3-96f6-7be2971fc13a.png)

This issue affects windows 7 systems connected to multiple monitors in a configuration in which the leftmost monitor is not the primary monitor. Under these circumstances, the dropdown menus are rendered incorrectly (See images). Both the primary dropdown (edit info/copy id/ quit) and the online/offline menu have this issue. This bug can be reproduced by configuring windows as shown in the attached screenshots. This behavior is not present when I change my display settings such that the leftmost monitor is the primary monitor

[more screenshots](http://imgur.com/a/TX6Vr)

**Comment by naxuroqa** [comment]
Closing as outdated, this has hopefully been fixed upstream in the meantime
