### ISSUE TITLE
JHBuild support

### ISSUE THREAD

**Issue by desiderantes** [naxuroqa/Venom#145]
It's a pain to build Venom right now, and jhbuild would alleviate the situation, making it very simple (modules, dependencies, etc :smile: ). Take a look at https://wiki.gnome.org/action/show/Projects/Jhbuild

**Comment by naxuroqa** [comment]
Closing as outdated, build system has been switched to meson.
Flatpak support should probably make this irrelevant.
Please reopen if you think this might still be useful
