### ISSUE TITLE
Ridiculously big CPU and RAM usage

### ISSUE THREAD

**Issue by zetok** [naxuroqa/Venom#149]
![2014-03-25 venom cpu ram](https://f.cloud.github.com/assets/3148759/2518963/008c15e0-b46b-11e3-9ccf-65b612b566ff.png)
↑ This.
Especially CPU. As of writing it, Venom is in unusable state. (Basically it's almost all the time hanged.)

I'm not sure what exactly caused it..
1. Very active group chat. I've been a 'member' of it without leaving it for days, and Venom seems to be really hanging and slowing down when this chat is selected (visible). Group chat to which SyncBot and GroupBot are inviting is really quiet in comparison.
2. Being a part of more than 1 group chat for days. (Perhaps it matters)
3. Having Venom open for days without turning it off. (I doubt that's really the case though)

I'm not sure what else info I could gather while Venom is running, and I'll keep it 'running' until it will become unbearable.

Oh, and afterthought: it would be nice if there was real threading support in Venom, so it could use more than 1 CPU core when hanging. It's kinda a waste that it uses only 1 core..

**Comment by naxuroqa** [comment]
Closing as outdated
