### ISSUE TITLE
Errors when I doubleclick on venom

### ISSUE THREAD

**Issue by WukkWill** [naxuroqa/Venom#152]
I downloaded Venom 32 bit for windows exe.

I get this error:

The procedure entry point iconv could not be located in the dynamic link library iconv.dll

I click okay, then I get this error:

Error loading C:\pathname\libgio~.dll  
(that last dll filename is not exactly verbatim)

I click okay and Venom comes up. Seems to be working. Have to add a friend.

Thanks to all the great guys at the irc chat!

My arch: 
Win XP AMD 32 bit

**Comment by naxuroqa** [comment]
Closing as outdated.
