### ISSUE TITLE
Feature request: Delivery receipts

### ISSUE THREAD

**Issue by SafwatHalaby** [naxuroqa/Venom#167]
The GUI should show the user that his message has arrived successfully, this is supported by the underlying tox protocol.

It should be something like Whatsapp's check marks:
![afd0b036625a3aa8b6399dc8c8fff0ff](https://cloud.githubusercontent.com/assets/5030488/2793202/dfc4a96a-cbdc-11e3-91d0-627caa4342c7.png)

Antox already does this.

**Comment by naxuroqa** [comment]
Closing as outdated, delivery receipts are now shown with an indicator
