### ISSUE TITLE
No way to set bootstrap node

### ISSUE THREAD

**Issue by zetok** [naxuroqa/Venom#175]
There's no option to set/use some node(s) other than default ones in Venom.
This situation causes problems for example in a case when there's breakage in protocol, and hardcoded bootstrap nodes haven't been updated yet.

Please fix it.

**Comment by naxuroqa** [comment]
Closing this as outdated. Bootstrap nodes are now retrieved from https://nodes.tox.chat/ on first startup and can be disabled. Refreshing them is in work.

**Comment by physkets** [comment]
But what @zetok requested can be a useful feature: i.e., to be able to manually add bootstrap nodes.

It will provide for a way to detach oneself from the one point of centralisation in the Tox network.

**Comment by naxuroqa** [comment]
@physkets I created a corresponding ticket #462
