### ISSUE TITLE
Keyboard with dead key issues on Windows 7

### ISSUE THREAD

**Issue by TheLastProject** [naxuroqa/Venom#196]
I have a friend running Windows 7 who complains about some issues with dead keys in Venom's input field.

To type something like `~"`, he has to type `~<SPACE>"<SPACE>`.

While this behaviour is partly logical, seeing as the user has a layout with dead keys, other applications let him type `~"` just fine, noticing that ~ can not be put on top of ". Therefore, Venom's behaviour here is inconsistent with other applications on the same platform.

I assume this to be an upstream GTK issue, but I figured reporting it anyway.

**Comment by naxuroqa** [comment]
Closing as outdated, this has hopefully been fixed upstream
