### ISSUE TITLE
Feature request: Choosing font size

### ISSUE THREAD

**Issue by TheLastProject** [naxuroqa/Venom#210]
It would be nice if users could change the font size in Venom settings. I personally know someone who has issues with small fonts and would greatly benefit from being able to increase the size. This doesn't necessarily have to be a pixel-perfect size, a few predefined settings like small/medium/large/huge would be quite useful for users with accessibility issues.

**Comment by naxuroqa** [comment]
Closing as outdated.
There is also this guide for setting large text at https://help.gnome.org/users/gnome-help/stable/a11y-font-size.html.en
