### ISSUE TITLE
Displaying images on Linux crashes Venom

### ISSUE THREAD

**Issue by TheLastProject** [naxuroqa/Venom#212]
I could've sworn this was already reported, but it turns out I'm wrong. Anyway:

Venom on Linux crashes when an image is displayed in the chat after sending it. Although I'd personally prefer the Tux3 way of displaying images in/after file transfers ( https://wiki.tox.im/images/5/5d/ToxGUI_tux3.png ) instead of displaying them in-chat, the client completely crashing is not a solution. This doesn't seem to happen on Windows, where the image displays fine.

Attached is a CC-BY-NC-ND-licensed image which can be used to reproduce the crash.

To reproduce:
1. Ensure at least one of the participants is using Venom on Linux
2. Send the file
3. Wait for the file transfer to complete

Expected result:
Image is displayed inline

Actual result:
Venom on Linux user crashes

Image:
![crazy language - cl-009 - rec_overflow - talking with my nord - cl009_wallpaper](https://cloud.githubusercontent.com/assets/1885159/3533137/77c8662e-07ca-11e4-8ae7-b4cf28ecbc60.jpg)

**Comment by naxuroqa** [comment]
Closing as outdated
