### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by VoteForNavalny** [naxuroqa/Venom#217]
[ERROR  ] Could not remove peer [5] from groupchat #1 (no such peer)
[ERROR  ] Sidebar could not remove peer #5
[ERROR  ] Group message from unknown contact #0 [1]
[ERROR  ] Group message from unknown contact #9 [0]
[FATAL  ]  venom_group_chat_contact_set_name: assertion 'self != NULL' failed
[FATAL  ]  venom_icontact_get_name_string: assertion 'self != NULL' failed
[FATAL  ]  venom_group_conversation_sidebar_update_contact_name: assertion 'new_name != NULL' failed

**Comment by naxuroqa** [comment]
Closing as outdated
