### ISSUE TITLE
Follow GNOME HIG.

### ISSUE THREAD

**Issue by GegoXaren** [naxuroqa/Venom#225]
I have been looking at Venom and have come to the conclusion that it does not follow the GNOME HIG.

Before we begin:
My "Status Menu" I mean the one with the blob that indicates ones status (online/away/busy/offline).

1) HeaderBar.
    When writing modern GTK+ application it is beneficial to use the provided GtkHeaderBar class.

2) Use Dark theme.
    In GTK+3 there is support for dark theme, this negates the need to overuse custom theming.
    (https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-application-prefer-dark-theme)

3) There are more than one way to do things.
    a) Preference can be accessed from the button in the contacts list and from the app menu.
    b) quit is in the status menu and the app menu.
    c) about is is the status menu and the app menu.

4) status menu is a mess.
    There are items there that have no place to be there.
        a) Export data file (Semantically incorrect, noting to do with status or user stuffs).
        b) About.
        c) Quit.
    Also there are icons on the menu items, this is deprecated and should not be used.

5) The status menu could use a GtkPopOver? (it is flexible and what not...)

6) Should not clicking on the "user icon" open up the edit user dialogue, and thus removing its need to be in the status menu?

**Comment by naxuroqa** [comment]
closed because outdated
