### ISSUE TITLE
Indicator for non-delivered messages.

### ISSUE THREAD

**Issue by vi** [naxuroqa/Venom#226]
Sometimes sent messages got [dropped](https://github.com/naxuroqa/Venom/issues/199#issuecomment-47965242). It whould be nice to have special indicators of such undelivered messages, like in Skype.

The indicator can be shown when messages is older than 1 minute and there is no delivery report for it.

**Comment by naxuroqa** [comment]
closing as outdated, not (yet) delivered messages get shown with an indicator
