### ISSUE TITLE
Selection of Text looks off

### ISSUE THREAD

**Issue by kiwistrongis** [naxuroqa/Venom#233]
Hi there. I'm not sure if it's my gtk theme or what, but selection of text looks off for me. Instead of the selection being highlighted in blue and text white as is usual, the text is not highlighted and is white, making it impossible to see.

OS: Fedora (Korora) 20
Venom version: 0.2.0r505
gtk theme: dorian-theme-3.10

**Comment by naxuroqa** [comment]
Closing as outdated
