### ISSUE TITLE
Sometimes urgent notification isn't set on new messages.

### ISSUE THREAD

**Issue by Jookia** [naxuroqa/Venom#240]
Sometimes my friends can just message me and I have no notifications. Adding some debug code, I found out that the 'is_active' property in the following code is sometimes true even if I'm on another workspace, regardless of the portion of the window I've clicked in or if it was focused before I moved workspaces.

```
    public void set_urgency () {
      if(!is_active && Settings.instance.enable_urgency_notification) {
        this.set_urgency_hint(true);
        this.set_title(_("* %s").printf(this.our_title));
      }
    }
```

I'm running Arch Linux using i3 and GTK2. I can't seem to find a way to reproduce it, it always seems to sneak up on me.

**Comment by naxuroqa** [comment]
Closing as outdated
