### ISSUE TITLE
[Linux][KDE] Venom overwrites clipboard

### ISSUE THREAD

**Issue by TheLastProject** [naxuroqa/Venom#248]
This has been annoying me for months and has often caused me to send the wrong content. The issue is that Venom overwrites the clipboard with the selected text once it gets focus.

How to reproduce:
1. Have someone send you text (sometimes, clicking a link seems to work too)
2. Select the text
3. Switch to another application and select text from there
4. Switch back to Venom and paste the text you just selected

Expected result:
The last selected text is pasted.

Actual result:
The last text sent is pasted, and I unknowingly send a YouTube link from Freddie Mercury to a friend as opposed to a link to a picture on Imgur.

EDIT: Updated title, please tell me if it also happens in other OSses or DEs.

**Comment by naxuroqa** [comment]
Closing as outdated
