### ISSUE TITLE
Allow configurable Ctrl Enter / Enter behavior

### ISSUE THREAD

**Issue by vn971** [naxuroqa/Venom#249]
Some people have habits of inserting a line break with Enter and sending the message with Ctrl Enter.
Could you please implement the appropriate functionality and settings in Venom?..

(My personal point of view is that Shift+Enter should insert a line break in any case.)

Related issue: #64.

**Comment by naxuroqa** [comment]
#383 will save accel keys (key bindings) to a file. Currently Enter without any modifier pressed will send, you can change that in the accels file.
