### ISSUE TITLE
[KDE]System tray icon looks misaligned and miscropped

### ISSUE THREAD

**Issue by TheLastProject** [naxuroqa/Venom#252]
![snapshot14](https://cloud.githubusercontent.com/assets/1885159/4260200/837b96d8-3b2f-11e4-9adf-2e7e0778c9da.png)

Venom's icon has more green space left of it than right of it on KDE and isn't centered. I'm not sure what causes it as all icons in icons/ seems to be fine, maybe it choses a wrong size icon under KDE?

**Comment by naxuroqa** [comment]
Closing as outdated.
