### ISSUE TITLE
Venom fails in tor-connected system

### ISSUE THREAD

**Issue by yurivict** [naxuroqa/Venom#257]
There is howto online instructing to run 'toxic --force-tcp --proxy 127.0.0.1 9050'. This is for 'toxic' and for tor-as-proxy situation.

I have the whole OS in VM, connected through tor. UDP is impossible, only TCP, an no proxy is needed. Venom doesn't have an option --force-tcp.

When I run venom, it takes a long time (10+ minutes) to get to 'online' status. Once online, I add some user ID to it. It says it sent the friend request, but the other account only gets it in 10+ minutes. Once accepted by the other account, the first account gets into "Offline" status for no apparent reason. Or, maybe, it just spontaneously gets into "Offline" status.

After a while friend request reply actually goes through, and users can talk, but the tor-connected system stays in "Offline" state. So they can talk in "Offline" state.

This behavior is quite misleading and faulty. Venom is dysfunctional under tor?

How to make it work?

venom-0.2.0

**Comment by naxuroqa** [comment]
Resolved in ced9296046c85ed596dd1a410a2b9304dace4498
