### ISSUE TITLE
No GUI updates after file transfer

### ISSUE THREAD

**Issue by MasX** [naxuroqa/Venom#262]
After a file transfer to an uTox user has been completed venom stops refreshing the GUI. No new messages are visible, though it does receive them as the log shows after a restart. Resizing the screen leads to white space. Note that when I was still running v 0.1.9 venom used to crash altogether after a file had been sent. 

Currently running venom v 0.2.0 on mint debian edition.

**Comment by drahnr** [comment]
@naxuroqa can you have a look at PR #286 which fixes the VAPI changes.

**Comment by naxuroqa** [comment]
Closing as outdated. File transfer is going to get reimplemented.
