### ISSUE TITLE
Buddy List scrollbar appears even when all items are visible on screen

### ISSUE THREAD

**Issue by yoasif** [naxuroqa/Venom#279]
Running 0.2.0r688. 

The buddy list that appears on the left side of the Venom window contains a scrollbar that is always present. This looks odd and is inconsistent with other GTK apps -- for an example, see Gedit. 

![screenshot from 2014-11-02 01 48 56](https://cloud.githubusercontent.com/assets/152493/4874410/fa536222-6253-11e4-8827-17b5f64c464f.png)

The scrollbar should not appear if all buddy list entries fit into the current window dimensions.

**Comment by naxuroqa** [comment]
Closing as outdated
