### ISSUE TITLE
Inconsistent theme colors: user menu vs. context menu in message input panel

### ISSUE THREAD

**Issue by yoasif** [naxuroqa/Venom#280]
May be a sub issue of #132, but wanted to reference it separately. 

Running 0.2.0r688.

I noticed that when clicking the status icon/menu and looking at the theme colors, it differs substantially from the colors in the context (right click) menu in the message input panel. 

See the screenshots below:

![screenshot from 2014-11-02 01 58 57](https://cloud.githubusercontent.com/assets/152493/4874442/32d86848-6256-11e4-979a-c7d58ef363ce.png)

![screenshot from 2014-11-02 01 59 59](https://cloud.githubusercontent.com/assets/152493/4874443/32dc5ac0-6256-11e4-9126-cce41d0f7492.png)

I don't quite understand the black background in the context menu, but in any case, it is inconsistent. I'd much prefer if Venom didn't try to override my GTK theme.

**Comment by naxuroqa** [comment]
Closing as outdated
