### ISSUE TITLE
Dependency on old version of gstreamer-plugins-bad?

### ISSUE THREAD

**Issue by kjcole** [naxuroqa/Venom#282]
I was recently cleaning the cruft out of my Ubuntu system and when I attempted to uninstall gstreamer-0.10-plugins-bad it claimed venom depended on it.  However, there is a gstreamer1.0-plugins-bad available in the repo... Can the deb package dependency be upgraded?

**Comment by naxuroqa** [comment]
gstreamer-0.10 and gstreamer-1.0 do not share the same api, which means the code has to be adapted to work with gstreamer-1.0.

**Comment by naxuroqa** [comment]
Adaptation is on its way
