### ISSUE TITLE
Is this still alive?

### ISSUE THREAD

**Issue by jurf** [naxuroqa/Venom#284]
The Tox wiki says Venom is deprecated and I can't compile Venom with the latest Tox.

**Comment by urras** [comment]
Nope, development on Venom has ceased.

**Comment by DoctorJellyface** [comment]
Know any active fork?

**Comment by mannol** [comment]
As far as I know there is no active fork of venom. However, you might want to check out our other clients such as [qTox](https://github.com/tux3/qTox).

**Comment by DoctorJellyface** [comment]
Already using qTox, but wanted to use Venom since I'm on GNOME.

**Comment by ProMcTagonist** [comment]
@DoctorJellyface  https://github.com/KoKuToru/gTox/

**Comment by DoctorJellyface** [comment]
Thanks man!

**Comment by v6** [comment]
// , How do I uninstall uTox and migrate its data?

**Comment by v6** [comment]
// , Just looking up [Venom][effort], checking the latest issues, [aaaaaaaaaaaand it's gone][$].

Hooray for alpha open source software. 'Tis a damnable shame. 

[effort]: https://github.com/naxuroqa/Venom/issues/284
[$]: https://youtu.be/-DT7bX-B1Mg?t=27s

**Comment by ProMcTagonist** [comment]
The uninstall method depends on how you installed it.

Your Tox profile should be in appdata or in ~/.config/tox

**Comment by bdheeman** [comment]
It's sad that the user's data and, or configuration is not sharable among
various Tox  UAs (User Agents).

Every user application or agent uses unique format and, or files :-(

**Comment by ProMcTagonist** [comment]
It's sharable among clients that weren't deprecated ages ago.

**Comment by SkyzohKey** [comment]
Bump! For peoples that have helped on Venom, I'm the only one developing [Ricin](https://github.com/RicinApp/Ricin) and I'm searching for contributors. Ricin is a modern Tox client written in Vala, using GTK+3 for the UI. It aims to be user-friendly and eye "candy" for the average user.

**Comment by naxuroqa** [comment]
@SkyzohKey Tell me if I can help you on anything with Ricin or Konv.

This project is as of now active again.

**Comment by SkyzohKey** [comment]
@naxuroqa Actually Ricin is deprecated as of now. Lol. I'm working a new platform-agnostic client that runs fine on Android/iOS/Windows Phone/Windows (UWP)/Linux/OSX and the web.

If this interests you, feel free to take a look at : https://github.com/Tox-Client/client

**Comment by naxuroqa** [comment]
@SkyzohKey I fear that I don't know enough about react to be of any help.

**Comment by SkyzohKey** [comment]
@naxuroqa Are you fine with Js? Also, feel free to ask if you need help with Venom! Your code really helped me when I was writting Ricin/Konv ;)

**Comment by SkyzohKey** [comment]
@naxuroqa If you want better mockups than @ItsDuke ones (even if I like them a lot), I've made some here => https://www.behance.net/gallery/52007569/Toxchat-redesign

**Comment by ItsDuke** [comment]
>https://www.behance.net/gallery/52007569/Toxchat-redesign

Very cool! Though we'll have to strap on our gloves when it comes to whose is "better" ;)

One of the main sticking points I've had in the few years I've spent doing UI work is that as slick and as functional as you plan it to be, it's only as good as it's users. If everyone else can't figure out your visual language, or even where you've stuck settings/features, you've missed the boat. Not to say that yours falls short anywhere, just a general word of warning for anyone cutting their teeth in that field.

**Comment by SkyzohKey** [comment]
Yeah didn't meant to be offensive Guy ! I'm all with you in that point.

**Comment by naxuroqa** [comment]
@smaragdus begone with your negativity.

Please see https://www.youtube.com/watch?v=rph_1DODXDU
