### ISSUE TITLE
Abstract *.ui files for ricing purposes

### ISSUE THREAD

**Issue by illeatmyhat** [naxuroqa/Venom#36]
It would be a good idea to allow the user to edit the *.ui files so they can rice without recompiling after changing the pixel width of a border or padding.

**Comment by naxuroqa** [comment]
ui files are being shipped inside a resource bundle in the application. Changing them means you will have to recompile. You can do e.g. css styling via the gtk inspection tool and .ui file development with glade to get a preview.
