### ISSUE TITLE
Venom AV when? Greetings from year 2013  :^)

### ISSUE THREAD

**Issue by towlie** [naxuroqa/Venom#400]
Nice to see that your are developing again here. And sorry for the issue spam . 

PS:
"Open source never dies"

**Comment by naxuroqa** [comment]
It's been a long time. As always, it's up for grabs.
I want to improve the code quality a bit, add more tests and add consistent storage first.
After that, definitely maybe.

**Comment by naxuroqa** [comment]
@towlie https://streamable.com/gbk9k

Soon (TM)
