### ISSUE TITLE
Can I use an existing profile?

### ISSUE THREAD

**Issue by physkets** [naxuroqa/Venom#461]
I'm currently using a profile I created in Toxic. I switched to qTox a while back, and it was able to detect the `.tox` file.

Can I use the same through Venom? When I start the client, I don't see any option to use an existing profile. Is there some config file I can alter, to achieve this?

Also, my profile is encrypted. Does that make a difference?

**Comment by physkets** [comment]
Also, should I copy the `.ini` file? Is that relevant to the profile?

**Comment by naxuroqa** [comment]
I don't think that the .ini file is of any use for venom, all files are of different structure and content except the tox data file.

As far as I am aware, the idea is for qTox also to use `$XDG_DATA_HOME/tox`, i.e. `~/.local/share/tox` in the future, might be already implemented. The next release will use this directory as well.

See the updated Tox Client Standard: https://github.com/Tox/Tox-Client-Standard/blob/master/data_storage/data_storage.md

And https://github.com/qTox/qTox/issues/5410

**Comment by naxuroqa** [comment]
Added an issue regarding the save file location #464
