### ISSUE TITLE
Groupchat text box larger than private chats

### ISSUE THREAD

**Issue by temp39714861974** [naxuroqa/Venom#81]
There's no way to make it smaller unless you type multiple lines.

![screenshot - 14-02-23 - 01 53 57 am](https://f.cloud.github.com/assets/6754737/2239714/2bbe83e8-9c4b-11e3-868a-2d5f248f99ff.png)
![screenshot - 14-02-23 - 01 54 25 am](https://f.cloud.github.com/assets/6754737/2239719/5214fad6-9c4b-11e3-91b4-dff07e33c779.png)

**Comment by naxuroqa** [comment]
Closing as outdated
