### ISSUE TITLE
'Send File' option broken | Ubuntu

### ISSUE THREAD

**Issue by bkamapantula** [naxuroqa/Venom#96]
I tried to send files (.png and .pdf) from Ubuntu to Mac 10.8.5. All I see is a black progress bar that doesn't update.

Has anyone else noticed this?

![venom](https://f.cloud.github.com/assets/1143687/2303629/4498f6d8-a1d6-11e3-9e8e-cbb74d29ea28.png)

**Comment by naxuroqa** [comment]
Closing as outdated
