### ISSUE TITLE
Allow updates for Win32 without full downloads

### ISSUE THREAD

**Issue by stqism** [naxuroqa/Venom#98]
Using either the rss feed or api, fetch the latest build of Venom based on number.
I can setup xdelta on the backend and using the premade Windows binaries we could switch up versions using a tiny amount of bandwidth and something that could be done in Python. We'd essentially patch the changes on to the zip folder, looking like a fresh download.

The RESTful API: http://jenkins.tox.im/job/venom_win32/api/
The RSS: http://jenkins.tox.im/job/venom_win32/rssAll
And xdelta: http://xdelta.org/

**Comment by naxuroqa** [comment]
Win32 is sadly not a priority anymore as the gtk3 cross platform support is not finished enough in my opinion
